In [1]:
import json
import zipfile
import pickle
import pandas as pd

In [ ]:
with open('data/pepe.json') as json_file:
    data = json.load(json_file)

with zipfile.ZipFile('data/laligaZIP.zip') as zip_ref:
    zip_ref.extractall('data')

with open('importante', 'rb') as f:
    a = pickle.load(f)
    b = pickle.load(f)
    c = pickle.load(f)

In [2]:
with zipfile.ZipFile('data/entrega_2.zip') as zip_ref:
    zip_ref.extractall('data/extracted')

In [3]:
with open('data/extracted/my_model', 'rb') as f:
    my_model0 = pickle.load(f)

In [6]:
my_model0

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=8)),
                ('kneighborsclassifier', KNeighborsClassifier(n_neighbors=7))])

In [2]:
df_test = pd.read_csv('data/extracted/test.csv')
df_test.head()

,Unnamed: 0,ingresos,gastos_comunes,pago_coche,gastos_otros,ahorros,vivienda,estado_civil,hijos,trabajo,target
0,95,4517,1310,89,529,25960,227634,2,2,6,1
1,15,5749,690,291,698,50257,305122,2,0,4,1
2,30,7422,1336,230,418,48257,338751,2,1,8,1
3,159,3504,1051,447,351,29890,313542,0,0,0,0
4,186,2308,577,152,657,33131,257224,0,0,2,0

In [3]:
df_test.columns[0]

'Unnamed: 0'

In [9]:
with open('data/extracted/info.json') as json_file:
    info = json.load(json_file)

In [10]:
info

{'nombre_alumno': 'Miguel Nievas',
 'titulo': 'PrediciÃ³n compra vs alquiler piso',
 'tipo_ml': 'C',
 'target': 'target'}

In [11]:
X_test=df_test.drop(columns=[info['target']])
y_test=df_test[[info['target']]]

In [15]:
score = my_model0.score(X_test,y_test)

In [19]:
df_results = pd.json_normalize(info)
df_results['score'] = score
df_results

   nombre_alumno                              titulo tipo_ml  target     score
0  Miguel Nievas  PrediciÃ³n compra vs alquiler piso       C  target  0.804878

In [20]:
df_results.to_csv('resultados_modelos.csv')

In [1]:
import os

In [2]:
os.listdir()

['data',
 'functions.py',
 'model_results.py',
 'my_notebook.ipynb',
 'resultados_modelos.csv',
 'trabajos',
 '__pycache__']

In [3]:
os.getcwd()

'c:\\Users\\Miguel Angel\\Documents\\Bootcamp_DS_1_22\\ds_thebridge_1_22\\3-Machine_Learning\\Entregas\\check_entrega2'

In [4]:
os.chdir(os.getcwd()+'/trabajos')

In [5]:
os.listdir()

['Alfonso Espinosa De Los Monteros - Proyecto Machine Learning _\xa0Modelo beta.docx',
 'Antonio Corbalán Navarro - Proyecto Machine Learning _\xa0Modelo beta.docx',
 'CryptoMachine.ipynb',
 'eda.ipynb',
 'entrega2_David_Fernandez.zip',
 'entrega2_ML.zip',
 'entregaML.zip',
 'EntregaML_07_04_héctor_tenor.rar',
 'EntregaML_2_Gretel De Cuyper.zip',
 'Entrega_1_ML_Miguel_La_Cruz.rar',
 'entrega_2.zip',
 'Entrega_2_Jhon_Moncaleano_Forero.rar',
 'franciscoPala.zip',
 'Health_index1.csv',
 'info(1).json',
 'info.json',
 'info_nic.json',
 'Laura_Cuesta_entrega_08_04_22.zip',
 'ML_Entrega 2_Miguel Chamochin.zip',
 'ML_Hugo.json',
 'ML_project_sales -Modelos.ipynb',
 'Modelo Beta ML.ipynb',
 'Modelo_Beta(1).zip',
 'Modelo_beta.zip',
 'Modelo_beta_Lorenzo.zip',
 'modelo_beta_LucyCampos.zip',
 'Model_1.7z',
 'model_v0',
 'model_v0.rar',
 'model_v0.zip',
 'my_model_1',
 'notebook.ipynb',
 'Pablo_Lopezosa_ENTREGA2(1).zip',
 'Pablo_Lopezosa_ENTREGA2(2).zip',
 'Pablo_Lopezosa_ENTREGA2.zip',
 'Prueba_ABC_chileno_copia.zip',
 'test(1).csv',
 'test.csv',
 'test.ipynb',
 'Z_Proyecto.rar']

In [10]:
for archivo in os.listdir():
    if archivo[-3:] == 'zip':
        print(archivo)
        # ejecutar script

entrega2_David_Fernandez.zip
entrega2_ML.zip
entregaML.zip
EntregaML_2_Gretel De Cuyper.zip
entrega_2.zip
franciscoPala.zip
Laura_Cuesta_entrega_08_04_22.zip
ML_Entrega 2_Miguel Chamochin.zip
Modelo_Beta(1).zip
Modelo_beta.zip
Modelo_beta_Lorenzo.zip
modelo_beta_LucyCampos.zip
model_v0.zip
Pablo_Lopezosa_ENTREGA2(1).zip
Pablo_Lopezosa_ENTREGA2(2).zip
Pablo_Lopezosa_ENTREGA2.zip
Prueba_ABC_chileno_copia.zip

In [11]:
from functions import load_files, test_results