# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [11]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [ ]:
food = pd.read_csv('./food_100.csv', index_col = ['Unamed: 0'])

In [14]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep = "\t", index_col = "order_id")
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Assign it to a variable called chipo.

In [15]:
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# Name of the max valued product

In [33]:
chipo['item_price'].str[1:].astype(float)

order_id
1        2.39
1        3.39
1        3.39
1        2.39
2       16.98
        ...
1833    11.75
1833    11.75
1834    11.25
1834     8.75
1834     8.75
Name: item_price, Length: 4622, dtype: float64

In [35]:
chipo['item_price'] = chipo['item_price'].str[1:].astype(float)
chipo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4622 entries, 1 to 1834
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   quantity            4622 non-null   int64
 1   item_name           4622 non-null   object
 2   choice_description  3376 non-null   object
 3   item_price          4622 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 180.5+ KB

In [36]:
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,Izze,[Clementine],3.39
1,1,Nantucket Nectar,[Apple],3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [46]:
chipo['item_price_unit'] = chipo['item_price'] / chipo['quantity']

In [48]:
chipo.head(20)

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,Izze,[Clementine],3.39,3.39
1,1,Nantucket Nectar,[Apple],3.39,3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
3,1,Side of Chips,NaN,1.69,1.69
4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25
5,1,Chips and Guacamole,NaN,4.45,4.45
6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75
7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
7,1,Chips and Guacamole,NaN,4.45,4.45
8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49,8.49
9,2,Canned Soda,[Sprite],2.18,1.09
10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75,8.75

In [43]:
chipo[chipo['item_price'] == chipo['item_price'].max()]  ### Ésta mola pero filtra todos los que tienen esos precios.

,quantity,item_name,choice_description,item_price
order_id,,,,
1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

In [42]:
chipo['item_price'].max()

44.25

In [90]:
column = chipo["item_price"]
max_value = column.max()

print(max_value)

44.25

In [39]:
list(chipo['item_price'])

[2.39,
 3.39,
 3.39,
 2.39,
 16.98,
 10.98,
 1.69,
 11.75,
 9.25,
 9.25,
 4.45,
 8.75,
 8.75,
 11.25,
 4.45,
 2.39,
 8.49,
 8.49,
 2.18,
 8.75,
 4.45,
 8.99,
 3.39,
 10.98,
 3.39,
 2.39,
 8.49,
 8.99,
 1.09,
 8.49,
 2.39,
 8.99,
 1.69,
 8.99,
 1.09,
 8.75,
 8.75,
 4.45,
 2.95,
 11.75,
 2.15,
 4.45,
 11.25,
 11.75,
 8.75,
 10.98,
 8.99,
 3.39,
 8.99,
 3.99,
 8.99,
 2.18,
 10.98,
 1.09,
 8.99,
 2.39,
 9.25,
 11.25,
 11.75,
 2.15,
 4.45,
 9.25,
 11.25,
 8.75,
 8.99,
 8.99,
 3.39,
 8.99,
 10.98,
 8.99,
 1.69,
 8.99,
 3.99,
 8.75,
 4.45,
 8.75,
 8.75,
 2.15,
 8.75,
 11.25,
 2.15,
 9.25,
 8.75,
 8.75,
 9.25,
 8.49,
 8.99,
 1.09,
 9.25,
 2.95,
 11.75,
 11.75,
 9.25,
 11.75,
 4.45,
 9.25,
 4.45,
 11.75,
 8.75,
 8.75,
 4.45,
 8.99,
 8.99,
 3.99,
 8.49,
 3.39,
 8.99,
 1.09,
 9.25,
 4.45,
 8.75,
 2.95,
 4.45,
 2.39,
 8.49,
 8.99,
 8.49,
 1.09,
 8.99,
 3.99,
 8.75,
 9.25,
 4.45,
 11.25,
 4.45,
 8.99,
 1.09,
 9.25,
 2.95,
 4.45,
 11.75,
 4.45,
 8.49,
 2.39,
 10.98,
 22.5,
 11.75,
 4.45,
 11.25,
 4.45,
 11.25,
 4.45,
 11.25,
 11.25,
 11.75,
 9.25,
 4.45,
 11.48,
 17.98,
 1.69,
 17.5,
 4.45,
 8.49,
 2.39,
 17.5,
 4.45,
 4.45,
 11.25,
 11.75,
 10.98,
 8.49,
 10.98,
 2.18,
 11.48,
 8.49,
 2.39,
 4.45,
 11.25,
 11.75,
 8.75,
 8.49,
 2.18,
 8.49,
 3.39,
 8.49,
 8.99,
 10.98,
 11.48,
 8.49,
 1.09,
 1.09,
 9.25,
 8.75,
 2.95,
 9.25,
 4.45,
 11.25,
 11.48,
 8.49,
 8.49,
 8.99,
 2.39,
 11.25,
 8.75,
 2.95,
 1.09,
 8.99,
 8.49,
 2.39,
 10.98,
 1.09,
 3.99,
 11.25,
 8.75,
 8.49,
 3.39,
 8.75,
 9.25,
 2.15,
 11.25,
 11.25,
 11.25,
 4.45,
 22.5,
 4.45,
 11.75,
 8.75,
 17.5,
 8.75,
 9.25,
 8.75,
 2.15,
 9.25,
 4.3,
 8.75,
 11.25,
 2.15,
 8.99,
 1.09,
 8.99,
 3.99,
 8.75,
 2.95,
 2.95,
 11.75,
 5.9,
 9.25,
 9.25,
 11.75,
 9.25,
 2.95,
 17.5,
 8.75,
 9.25,
 10.98,
 8.99,
 1.09,
 1.09,
 1.09,
 8.99,
 10.98,
 1.09,
 8.75,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 8.99,
 8.99,
 8.99,
 1.09,
 11.75,
 1.25,
 8.99,
 2.39,
 9.25,
 2.95,
 8.99,
 3.99,
 8.49,
 2.39,
 8.49,
 8.49,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 1.69,
 1.09,
 23.78,
 17.5,
 2.15,
 8.75,
 9.25,
 9.25,
 8.75,
 4.45,
 8.75,
 11.25,
 11.25,
 1.25,
 9.25,
 4.45,
 11.25,
 11.75,
 11.75,
 6.49,
 8.99,
 2.39,
 8.49,
 2.39,
 11.25,
 8.75,
 2.15,
 8.99,
 1.69,
 8.75,
 11.25,
 2.15,
 4.45,
 8.75,
 8.49,
 8.99,
 17.5,
 8.49,
 1.09,
 1.09,
 8.75,
 1.25,
 2.15,
 11.08,
 8.49,
 8.49,
 8.99,
 2.39,
 8.75,
 2.15,
 1.5,
 11.25,
 2.15,
 8.49,
 8.49,
 11.75,
 9.25,
 11.75,
 1.25,
 11.25,
 8.75,
 4.45,
 6.49,
 9.25,
 2.95,
 11.25,
 4.45,
 1.25,
 1.25,
 8.49,
 2.39,
 2.18,
 8.49,
 2.18,
 22.16,
 17.5,
 8.75,
 2.95,
 6.49,
 8.99,
 3.39,
 3.39,
 8.99,
 8.49,
 11.25,
 2.15,
 11.25,
 2.95,
 11.25,
 1.25,
 8.99,
 1.09,
 8.75,
 8.75,
 9.25,
 2.95,
 11.75,
 1.5,
 8.99,
 1.09,
 11.25,
 1.25,
 1.25,
 11.25,
 11.75,
 2.15,
 8.99,
 1.69,
 11.75,
 6.49,
 8.75,
 9.25,
 11.25,
 4.45,
 1.25,
 11.25,
 4.45,
 8.49,
 8.99,
 8.49,
 8.99,
 11.25,
 1.25,
 11.75,
 1.25,
 11.75,
 9.25,
 4.45,
 11.25,
 2.15,
 32.94,
 1.25,
 11.25,
 11.48,
 1.69,
 1.09,
 17.5,
 4.45,
 6.49,
 9.25,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 2.15,
 2.95,
 17.5,
 10.98,
 11.48,
 11.48,
 3.39,
 8.99,
 1.69,
 8.99,
 1.09,
 10.98,
 3.39,
 8.99,
 1.09,
 9.25,
 8.75,
 11.25,
 4.45,
 2.95,
 9.25,
 22.2,
 8.49,
 8.99,
 8.75,
 8.75,
 11.75,
 8.75,
 11.25,
 9.25,
 11.25,
 11.25,
 8.75,
 11.25,
 2.95,
 1.25,
 8.49,
 1.69,
 11.75,
 11.25,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.49,
 3.99,
 11.48,
 1.69,
 1.09,
 11.25,
 1.5,
 10.58,
 1.69,
 9.25,
 11.25,
 8.75,
 9.25,
 11.25,
 11.25,
 8.75,
 11.75,
 8.75,
 8.75,
 8.75,
 2.15,
 11.25,
 11.75,
 2.5,
 4.45,
 9.25,
 4.45,
 11.25,
 8.49,
 3.99,
 9.25,
 9.25,
 11.25,
 9.25,
 11.75,
 11.25,
 1.25,
 23.5,
 1.25,
 8.99,
 8.49,
 7.4,
 7.4,
 8.75,
 1.25,
 4.45,
 8.75,
 2.15,
 8.75,
 4.45,
 7.4,
 7.4,
 7.4,
 8.99,
 3.99,
 8.99,
 1.69,
 8.75,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 2.95,
 8.75,
 18.5,
 8.49,
 3.99,
 2.95,
 9.25,
 9.25,
 3.0,
 1.25,
 8.75,
 9.25,
 4.45,
 8.75,
 11.25,
 4.45,
 10.98,
 22.16,
 4.45,
 8.75,
 9.25,
 6.49,
 9.25,
 11.25,
 8.75,
 9.25,
 2.15,
 9.25,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 9.25,
 1.25,
 1.25,
 8.75,
 8.75,
 9.25,
 4.45,
 11.75,
 11.75,
 11.75,
 9.25,
 9.25,
 16.98,
 2.39,
 3.39,
 3.39,
 9.25,
 11.75,
 11.25,
 2.15,
 8.75,
 9.25,
 4.45,
 10.98,
 11.25,
 9.25,
 22.5,
 9.25,
 2.95,
 1.5,
 11.48,
 8.49,
 1.69,
 8.49,
 8.49,
 8.49,
 6.78,
 11.75,
 4.45,
 8.75,
 4.45,
 11.89,
 9.39,
 8.75,
 2.95,
 1.25,
 9.25,
 8.75,
 23.78,
 8.75,
 9.25,
 2.15,
 2.15,
 1.25,
 8.49,
 3.99,
 10.98,
 1.09,
 8.75,
 4.45,
 8.75,
 11.75,
 2.95,
 4.45,
 9.25,
 8.75,
 8.49,
 3.99,
 22.5,
 11.25,
 1.25,
 8.75,
 8.75,
 18.5,
 6.49,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.99,
 1.09,
 8.49,
 2.39,
 11.48,
 1.69,
 2.5,
 9.25,
 1.5,
 17.5,
 2.95,
 8.75,
 4.45,
 11.75,
 8.75,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 8.99,
 3.99,
 8.99,
 11.25,
 4.45,
 1.25,
 3.99,
 10.98,
 7.4,
 3.0,
 7.4,
 4.0,
 8.49,
 3.99,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 2.15,
 11.25,
 4.45,
 3.75,
 11.75,
 8.99,
 2.39,
 8.75,
 4.45,
 1.25,
 8.99,
 8.49,
 2.18,
 8.49,
 2.18,
 1.09,
 8.75,
 2.95,
 1.25,
 1.5,
 11.25,
 9.25,
 2.95,
 1.25,
 8.49,
 3.99,
 11.48,
 3.99,
 8.49,
 11.25,
 1.25,
 8.99,
 1.69,
 11.25,
 1.25,
 6.49,
 8.75,
 9.25,
 8.75,
 2.95,
 8.75,
 11.75,
 8.69,
 8.69,
 2.29,
 3.99,
 8.49,
 8.75,
 8.75,
 1.25,
 11.75,
 11.25,
 11.25,
 11.25,
 1.25,
 9.25,
 11.75,
 6.49,
 3.99,
 8.49,
 11.25,
 2.15,
 11.25,
 11.89,
 8.99,
 1.69,
 8.99,
 8.99,
 3.99,
 8.99,
 9.25,
 9.25,
 2.15,
 7.4,
 7.4,
 8.75,
 8.75,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 11.25,
 1.25,
 3.99,
 8.49,
 8.49,
 8.49,
 8.99,
 8.75,
 2.15,
 1.25,
 8.49,
 1.09,
 1.09,
 8.75,
 2.95,
 1.25,
 9.25,
 1.25,
 2.15,
 11.25,
 1.25,
 4.45,
 8.75,
 2.5,
 8.9,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 10.98,
 3.99,
 10.98,
 3.99,
 1.69,
 8.99,
 9.25,
 8.75,
 8.99,
 1.09,
 9.25,
 2.95,
 8.75,
 9.25,
 3.99,
 8.49,
 8.75,
 8.75,
 22.5,
 10.98,
 3.27,
 3.99,
 8.99,
 1.09,
 11.08,
 8.75,
 4.45,
 11.08,
 3.99,
 8.49,
 4.3,
 9.25,
 8.75,
 11.25,
 11.25,
 9.25,
 8.49,
 8.99,
 8.49,
 8.75,
 2.95,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 11.25,
 4.45,
 16.98,
 8.49,
 2.39,
 11.25,
 3.75,
 9.25,
 4.45,
 9.25,
 9.25,
 4.45,
 8.75,
 9.25,
 8.75,
 9.25,
 9.25,
 9.25,
 11.48,
 8.99,
 22.5,
 11.75,
 11.25,
 1.25,
 8.75,
 2.15,
 1.25,
 11.25,
 8.75,
 1.25,
 11.25,
 1.5,
 11.25,
 11.25,
 9.25,
 6.49,
 8.9,
 8.75,
 4.45,
 11.25,
 1.25,
 17.5,
 9.25,
 8.75,
 11.75,
 3.0,
 8.49,
 8.49,
 10.98,
 8.99,
 3.99,
 8.75,
 4.45,
 8.99,
 1.69,
 11.75,
 8.75,
 11.25,
 4.45,
 11.75,
 1.25,
 11.75,
 2.95,
 8.99,
 8.99,
 2.18,
 17.98,
 8.99,
 8.49,
 1.69,
 11.75,
 11.25,
 2.95,
 3.75,
 9.25,
 11.75,
 8.75,
 2.15,
 1.5,
 8.49,
 8.49,
 3.39,
 8.69,
 3.89,
 8.75,
 4.45,
 8.75,
 11.25,
 2.15,
 8.75,
 8.49,
 1.69,
 8.49,
 8.49,
 1.25,
 8.75,
 11.75,
 11.75,
 8.99,
 1.09,
 8.75,
 4.45,
 8.75,
 2.95,
 8.75,
 2.15,
 3.99,
 8.49,
 8.99,
 3.99,
 8.49,
 1.69,
 1.09,
 8.99,
 1.09,
 9.25,
 8.75,
 8.99,
 2.39,
 1.25,
 1.25,
 11.25,
 11.25,
 9.25,
 9.25,
 11.25,
 1.5,
 3.99,
 8.49,
 11.25,
 9.25,
 11.25,
 17.5,
 8.75,
 8.9,
 8.75,
 8.75,
 8.99,
 2.39,
 11.25,
 9.25,
 2.15,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 11.75,
 1.25,
 11.25,
 11.25,
 8.49,
 10.98,
 8.75,
 1.25,
 8.75,
 ...]

### Step 4. How many products cost more than $10.00?

In [55]:
chipo.loc[chipo.item_price > 10.00, ['item_price']]

          item_price
order_id
2              16.98
3              10.98
4              11.75
7              11.25
12             10.98
...              ...
1830           11.75
1830           11.25
1833           11.75
1833           11.75
1834           11.25

[1130 rows x 1 columns]

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [60]:
print(chipo[['item_name', 'item_price_unit']])

                                      item_name  item_price_unit
order_id
1                  Chips and Fresh Tomato Salsa             2.39
1                                          Izze             3.39
1                              Nantucket Nectar             3.39
1         Chips and Tomatillo-Green Chili Salsa             2.39
2                                  Chicken Bowl             8.49
...                                         ...              ...
1833                              Steak Burrito            11.75
1833                              Steak Burrito            11.75
1834                         Chicken Salad Bowl            11.25
1834                         Chicken Salad Bowl             8.75
1834                         Chicken Salad Bowl             8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [63]:
chipo.sort_values(by=['item_name'], ascending=False)   # True si lo quieres ascendente, False Descendente.

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49
1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
...,...,...,...,...,...
774,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
465,1,6 Pack Soft Drink,[Coke],6.49,6.49
1517,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
566,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1448,1,6 Pack Soft Drink,[Nestea],6.49,6.49

In [ ]:
#agrupamos por iten_name y luego la media de cada uno (al final es el mismo precio)
precio_item_name = chipo.groupby('item_name',sort=True)['item_price'].mean()
display(precio_item_name.round(2))

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [68]:
chipo[chipo['item_price'] == chipo['item_price'].max()]['quantity'].values[0]

15

In [69]:
chipo[chipo['item_price'] == chipo['item_price'].max()]['quantity']

order_id
1443    15
Name: quantity, dtype: int64

In [89]:
chipo[chipo['item_price'] == chipo['item_price'].max()]

,quantity,item_name,choice_description,item_price,item_price_unit
order_id,,,,,
1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95

V2

In [77]:
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

order_id
1443    15
1443     7
1443     1
1443     3
1443     4
1443     3
1443     2
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [79]:
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].count()

quantity              18
item_name             18
choice_description    18
item_price            18
item_price_unit       18
dtype: int64

### Step 9. How many times did someone order more than one Canned Soda?

In [87]:
len(chipo[(chipo['item_name']=='Canned Soda') & (chipo['quantity']>1)])

20

In [85]:
chipo[(chipo['item_name']== 'Canned Soda') & (chipo['quantity']>1)].shape[0]

20

In [84]:
chipo[(chipo['item_name']== 'Canned Soda') & (chipo['quantity']>1)].count()

quantity              20
item_name             20
choice_description    20
item_price            20
item_price_unit       20
dtype: int64